# Generated by Django 6.0.3 on 2026-03-18 01:06

import mascotas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fecha_ingreso',
            field=models.DateField(validators=[mascotas.models.validar_fecha_ingreso]),
        ),
    ]
