# Generated by Django 6.0.3 on 2026-04-06 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_fotomascota_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad_anios',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='especie',
            field=models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En proceso'), ('adoptada', 'Adoptada'), ('inactiva', 'Inactiva')], db_index=True, default='disponible', max_length=20),
        ),
    ]
