# Generated by Django 6.0.3 on 2026-03-06 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('deposito', 'Depósito bancario'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], max_length=20)),
                ('comprobante', models.ImageField(blank=True, upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('verificada', 'Verificada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_donacion', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donación',
                'verbose_name_plural': 'Donaciones',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
