# Generated by Django 6.0.3 on 2026-04-06 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('verificada', 'Verificada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
