# Generated by Django 6.0.3 on 2026-04-06 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_mensajescontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='capacidad',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('proximo', 'Próximo'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='proximo', max_length=20),
        ),
    ]
